# Generated by Django 5.2.4 on 2025-11-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_customuser_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='must_change_password',
        ),
    ]
