# Generated by Django 5.2.4 on 2025-11-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_customuser_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='must_change_password',
        ),
    ]
