# Generated by Django 5.2.4 on 2025-11-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('BA', 'Business Administration'), ('IT', 'Information Technology'), ('TM', 'Tourism Management'), ('BE', 'Basic Education'), ('CRM', 'Criminology')], default='BE', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_Image_Url',
            field=models.URLField(blank=True),
        ),
    ]
