# Generated by Django 5.2.4 on 2025-11-19 01:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_customuser_managers_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_Image_Url',
        ),
    ]
