# Generated by Django 5.2.4 on 2025-11-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_customuser_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isFirstLogin',
            field=models.BooleanField(default=True),
        ),
    ]
