# Generated by Django 5.2.4 on 2025-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_customuser_isfirstlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='userRole',
            field=models.CharField(choices=[('staff/checker', 'Staff/Checker'), ('admin', 'Admin')], default='staff/checker', max_length=15),
        ),
    ]
