# Generated by Django 5.2.4 on 2026-01-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_remove_customuser_is_owner_alter_profile_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
