from .auth_views import *
from .dashboard_views import *
from .accounts_views import *
from .semester_views import *
from .schedule_views import *
from .reports_views import *
from .schoolyear_views import *
from .staffhome_views import *
from .staff_dashboard import *
from .staff_addsub import *
from .staff_scheduling import *
from .staff_tertiaryfaculty import *
from .staff_schoolyear import *
